### PR TITLE
Add Weighted EP Models

### PR DESCRIPTION
**Pull request by CroppedClamp**
Adding into the repository the 21 models that have been weighted by year, in order to allow for era adjustments. These models include underlying data files, which is by the binaries are so big

### CODE REVIEW

**Comment by guga31bb** [comment]
Hooray thank you! A few questions and sorry if these are dumb questions as this project has been my first real experience with github and Seb is probably already asleep:
1. Is the code used to generate these models included somewhere? The hope is that everything provided by the package can be re-producible
2. There shouldn't be a need to provide the underlying data since that's provided by the package right? Eg here's how the CP model is estimated, which starts by loading the data: https://github.com/mrcaseb/nflfastR/blob/master/data-raw/CP.R
3. This question is probably especially dumb but nflscrapR has included functions for applying the EP & WP models, is there something like that here?

**Comment by mrcaseb** [comment]
OK I took a look at the models and am pretty sure it's not that hard to include them in the package. But there is some work to manage it:

1. We can't build in those large files into the package. When comparing to the [nflscrapR models](https://github.com/maksimhorowitz/nflscrapR/blob/master/R/sysdata.rda?raw=true) they didn't built in the underlying data. Is there an option to not include those data when creating the model? I can not remove them from the models because this changes the class from `nnet` to `list` and therefore brakes the `predict` method. It's the same question for the wp model. Those files need to be as small as possible for package integration because all of them are loaded to memory when using the package.
1. Since every season has it's own model there is the question how we compute ep for a running season. Use 2019 for 2020? How long? When do we add the model for 2020? 
The most critical point: We need a script how to create the model so we are able to build it when the time has come (e.g. half of the season is gone). If we have that script we hopefully can solve point 1.

All in all I'd say we need a script to create the models @CroppedClamp (See Ben's question 1.). This would help us update the model during a season and in sense of open source it would be good for people out there to know how the models are built.

@guga31bb we need to rewrite the functions to predict and add ep and wp but we could start with just copying them and change the way how the model is loaded right before the `predict` call. In a first step this is everything we need to do but I think there is also some additional potential to optimize the code.

**Comment by CroppedClamp** [comment]
1) Yes, I will include code
2) Yes, that was my bad haha, these binaries are huge
3) Yeah, we would have to rebuild the code, just wanted to get the models here first

**Comment by CroppedClamp** [comment]
Model data has been removed. Shrunk the binaries by about 99.9% lol

**Comment by guga31bb** [comment]
If it's helpful @CroppedClamp, going to put some functions I made [here](https://gist.github.com/guga31bb/2516d034ca37ab223f9f4b9700ae5bda). I was playing with EP models last week -- basically trying to make something compatible with nflfastR -- but with the new API ran out of time.

I'm not tied to the EP model in here and was just using this to convince myself that the `add_ep_variables()` function would work with our code, you've done a lot more work on making the model so will defer to you on the actual model. If this looks close to your model you can just change whatever is in the nnet call and it should be compatible.

One more thing to raise: [Zach Feldman was playing around with CPOE](https://github.com/z-feldman/Expected_Completion_NFL/blob/master/XGBoost.R) and found that xgboost works better than the GAMs we were using and I started wondering if we should try that for the EP models too.

**Comment by CroppedClamp** [comment]
@guga31bb Yes, they absolutely are just plug-and-play. The code for that hasn't been implemented yet for that, the point of this MR was just to get the binaries into the repo and split up the PR process for better review and commit tracking.

As for xgboost/GAM--agreed, I think that's a pretty good idea. The current code here is using `nnet`, as it adheres closest to the original intent of Yurko's paper and EPA understanding in general, with weighting and CV validation added for eras, etc. Theoretically, those future models should be plug and play as well, and should be able to be PR-ed into the repo as well in future iterations if we can set up per-year models, as I think the data has borne out. I have been working on running those as well.

Think this makes sense for CPOE as well, which was also discussed with Feldman, and I think we should add in those models as well.

**Comment by mrcaseb** [comment]
Going to close this Nick because there will be new `xgboost` models in the upcoming version. Thanks much for the contribution!

**Pull request closed without merging**
