### PR TITLE
Implement fastrmodels

### PR DESCRIPTION
**Pull request by mrcaseb**

### CODE REVIEW

**Comment by mrcaseb** [comment]
Needs some further testing.

**Comment by mrcaseb** [comment]
Also exports the `field_descriptions` and `stat_ids` data frames

**Comment by guga31bb** [comment]
Thoughts on leaving the `vegas_wp` and `ep` models in `nflfastR` since those are the only ones that are likely to ever be re-tuned?

It might make sense to just leave those 2 in the package so that we don't have to re-write everything when those models are re-done.

**Comment by mrcaseb** [comment]
> 
> 
> Thoughts on leaving the `vegas_wp` and `ep` models in `nflfastR` since those are the only ones that are likely to ever be re-tuned?
> 
> It might make sense to just leave those 2 in the package so that we don't have to re-write everything when those models are re-done.

Honestly I'd like to remove them for now because especially the ep model is so huge. If there will be an update in the future we can easily try to get it into fastrmodels and only put it back in nflfastR if they reject it. It's just cleaner

**Comment by guga31bb** [comment]
Ok sounds good!

**Pull request merged**
