### PR TITLE
more PAT fixes

### PR DESCRIPTION
**Pull request by guga31bb**
Fixes for 

https://github.com/mrcaseb/fastscraper/issues/283
https://github.com/mrcaseb/fastscraper/issues/280
https://github.com/mrcaseb/nflfastR/issues/49

### CODE REVIEW

**Comment by guga31bb** [comment]
Can you replicate these check errors? It works fine on my machine so I am very confused

**Comment by mrcaseb** [comment]
It is happening in the tests when trying to run add_ep(). I guess this is a dplyr v1 problem if it is running on your machine.

**Comment by guga31bb** [comment]
lol I'm an idiot but fixed. Good thing we wrote those unit tests to catch stuff like this

**Comment by mrcaseb** [comment]
Oh I see. That .data$ was costly lol

**Comment by mrcaseb** [comment]
I should have written a test for update_db() as well ha

**Comment by guga31bb** [comment]
Ok I think this is ready

**Pull request merged**
