### PR TITLE
Scramble fix

### PR DESCRIPTION
**Pull request by mrcaseb**
Fix for 2005 qb scrambles. (https://github.com/mrcaseb/fastscraper/issues/279)

### CODE REVIEW

**Comment by mrcaseb** [comment]
``` r
library(nflfastR)
library(dplyr)

pbp_old <- load_pbp(2005, TRUE)

pbp_new <- fast_scraper_schedules(2005) %>% fast_scraper()

pbp_old %>% group_by(season) %>% summarise(s = sum(qb_scramble, na.rm = TRUE))
#> # A tibble: 1 x 2
#>   season     s
#> *  <int> <dbl>
#> 1   2005    49
pbp_new %>% group_by(season) %>% summarise(s = sum(qb_scramble, na.rm = TRUE))
#> # A tibble: 1 x 2
#>   season     s
#> *  <int> <dbl>
#> 1   2005   592
```

**Comment by mrcaseb** [comment]
Ok I _thik_  `pass` will account correctly for `qb_scramble` but I have not solution yet how to fill `passer` for those fixed 2005 scrambles because the string extraction doesn't work

**Comment by guga31bb** [comment]
Can we do something like passer = rusher if season == 2005 and scramble ==
1? And set rusher = NA?

**Comment by guga31bb** [comment]
I think the .xlsx is ok to push if we trim down to only the columns needed to do the scramble_fix first

**Pull request merged**
