### PR TITLE
fix decoding description and fantasy stats

### PR DESCRIPTION
**Pull request by guga31bb**

### CODE REVIEW

**Comment by guga31bb** [comment]
Updated everything but looking at the [leaderboards](https://www.nfl.com/stats/player-stats/category/rushing/2020/POST/all/rushingyards/desc), we're missing a Josh Jacobs carry and 2 Nick Chubb rushing yards:

``` r
nflfastR::load_pbp(2020) %>%
    dplyr::filter(week <= 17, !is.na(down), !is.na(rusher_player_name)) %>%
    dplyr::group_by(rusher_player_name, posteam) %>%
    dplyr::summarize(
        yards = sum(rushing_yards, na.rm = T),
        tds = sum(touchdown == 1 & td_team == posteam),
        att = dplyr::n()
    ) %>%
    dplyr::arrange(-yards) %>%
    ungroup() %>%
    dplyr::slice(7:8)
   
# A tibble: 2 x 5
  rusher_player_name posteam yards   tds   att
  <chr>              <chr>   <dbl> <int> <int>
1 J.Jacobs           LV       1066    12   274
2 N.Chubb            CLE      1065    12   190
```

image

**Comment by mrcaseb** [comment]
The 2 missing Nick Chubb Yards are probably in `lateral_rushing_yards`. 

Jacobs is strange as it's too many yards and carries. Like there is a play that shouldn't count.

**Comment by guga31bb** [comment]
> The 2 missing Nick Chubb Yards are probably in `lateral_rushing_yards`.

This is accurate. Updated the .rmd.

Fixed Jacobs by using `play_type` run or qb_kneel. Okay I think we're finally good on this

**Comment by mrcaseb** [comment]
I'd expect Chubb's attempts are wrong as lateral yards don't count as attempt.

**Comment by guga31bb** [comment]
Dangit you're right

**Comment by guga31bb** [comment]
Just moving all this to the other branch

**Pull request closed without merging**
