### PR TITLE
Make `penalty_fix==0` when `penalty==1` and `play_type_nfl=="PENALTY"`

### LINKED ISSUE #172: `play_type != "no_play"` in rare penalty situation
Also see https://github.com/guga31bb/nflfastR-data/issues/45

### PR DESCRIPTION
**Pull request by mrcaseb**
closes #172

### CODE REVIEW

**Comment by mrcaseb** [comment]
There is only a single play in the 2011:2020 data where this bug occurred and I hope it's fixed now

``` r
library(magrittr)
nflfastR:::load_pbp(2011:2020) %>% 
  dplyr::filter(penalty == 1, play_type != "no_play", play_type_nfl == "PENALTY") %>% 
  dplyr::select(game_id, play_id, play_type, play_type_nfl, penalty)

#> # A tibble: 1 x 5
#>   game_id        play_id play_type play_type_nfl penalty
#>   <chr>            <dbl> <chr>     <chr>           <dbl>
#> 1 2020_10_DEN_LV     979 run       PENALTY             1

nflfastR::fast_scraper("2020_10_DEN_LV") %>% 
  dplyr::filter(penalty == 1, play_type != "no_play", play_type_nfl == "PENALTY") %>% 
  dplyr::select(game_id, play_id, play_type, play_type_nfl, penalty)

#> # A tibble: 0 x 5
#> # … with 5 variables: game_id <chr>, play_id <dbl>, play_type <chr>,
#> #   play_type_nfl <chr>, penalty <dbl>
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mrcaseb** [comment]
The relevant play is now correctly classified as `no_play`

``` r
library(magrittr)
nflfastR::fast_scraper("2020_10_DEN_LV") %>% 
  dplyr::filter(play_id == 979) %>% 
  dplyr::select(game_id, play_id, play_type, play_type_nfl, penalty)

#> # A tibble: 1 x 5
#>   game_id        play_id play_type play_type_nfl penalty
#>   <chr>            <dbl> <chr>     <chr>           <dbl>
#> 1 2020_10_DEN_LV     979 no_play   PENALTY             1
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mrcaseb** [comment]
I have tested the fix and it only affects the total rush epa, wpa etc. numbers in the given game so it should be save to merge it

**Comment by mrcaseb** [comment]
Just added a fix for the pre 2016 JAX games bug in #174. This time `penalty_team`

``` r
library(magrittr)

nflfastR:::load_pbp(2013) %>% 
  dplyr::filter(game_id == "2013_01_KC_JAX", !is.na(penalty_team)) %>% 
  dplyr::count(penalty_team)
#> # A tibble: 1 x 2
#>   penalty_team     n
#> * <chr>        <int>
#> 1 KC               8

nflfastR::fast_scraper("2013_01_KC_JAX") %>% 
  dplyr::filter(!is.na(penalty_team)) %>% 
  dplyr::count(penalty_team)

#> # A tibble: 2 x 2
#>   penalty_team     n
#> * <chr>        <int>
#> 1 JAC              5
#> 2 KC               3
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by guga31bb** [comment]
Looks good. Note that `clean_pbp()` will change `penalty_team` from `JAC` to `JAX` in your example above (as is intended)- I made sure this is the case. I think this can be merged in!

**Pull request merged**
