### PR TITLE
Add xpass

### PR DESCRIPTION
**Pull request by guga31bb**

### CODE REVIEW

**Comment by guga31bb** [comment]
I haven't had a chance to fully test the model (like building a calibration plot) but in terms of the actual stuff that needs to be in `nflfastR`, I think this is ready. The model lives in `nflfastR-data` anyway.

**Comment by mrcaseb** [comment]
I will make minor modifications to the last message and the arguments to make it consistent with all the other functions. 

We can add this function to the wrapper as well, right?

**Comment by guga31bb** [comment]
> We can add this function to the wrapper as well, right?

Over the offseason yes, but not yet since it adds columns

**Comment by mrcaseb** [comment]
Agree. I will add it and comment it out so we don't forget.

**Comment by guga31bb** [comment]
Oh and in the order it needs to come after `clean_pbp()` since it uses some columns from there

**Comment by mrcaseb** [comment]
Yeah I read that in the docs. Would have just added it to the end of the wrapper (behind `add_xyac()` anyway.

**Pull request merged**
