### PR TITLE
fix series and fixed_drive for muffed punts

### PR DESCRIPTION
**Pull request by guga31bb**

### CODE REVIEW

**Comment by guga31bb** [comment]
I think this closes https://github.com/mrcaseb/nflfastR/issues/130 too right?

**Comment by mrcaseb** [comment]
Ha I was asking this myself too. Honestly I don't know. Since that issue was filed we have fixed the PAT bug and now the muffed punts. I didn't look **that** close to the remaining issues with series and drive so I can't tell if there are more edge case issues. 

We could close it with the comment that it can be reopened in case there are still problems.

**Comment by mrcaseb** [comment]
The cross reference to the issue in `News.md` can be done like on GitHub. So instead of pasting the link you can just do #xyz

**Comment by guga31bb** [comment]
Looking a little more I think the only edge case left is fixed_drive and series incrementing on the kickoff attempt of a recovered onside kick. These are so rare I don't think I care to fix them. So I'll link that issue here too.

**Pull request merged**
