### PR TITLE
add field names vignette and dataframe object, and pkgdown heading

### PR DESCRIPTION
**Pull request by tanho63**

### CODE REVIEW

**Comment by mrcaseb** [comment]
The new df and the VignetteBuilder field are causing R-CMD check NOTES that will cause problems with cran. If it's ok, @tanho63, I will make some modifications in the PR to avoid these. 

My idea:
-- put the new df in data-raw and load it remotely from GitHub for the new vignette so it's not inside the package
-- remove VignetteBuilder field and knitr suggestion from DESCRIPTION
this should avoid the NOTES and the vignette will still work

**Comment by tanho63** [comment]
Hmm, removing from the data folder means it won’t be available to R users as `nflfastr::field_descriptions` - looking at the notes, it’s just complaining about vignette builder in the description right?

 (The other complaints are package size/component size which aren’t related to the new vignette?)

**Comment by tanho63** [comment]
Looks like notes from latest commit of this PR are the same as the current notes on master branch?

**Comment by mrcaseb** [comment]
The package size NOTE on Windows is the problem. We are very close to 5MB (on Windows, Mac exceeds 5MB for some reason) but before the new df we didn't exceed that limit (you can compare to the other PR check results on Windows). CRAN incoming check is done on Windows so that's the reason why I don't want package size NOTES on Windows. 

Removing the df from the package (for now) is the only solution but we can still host the file on GitHub.

I will move the models to a separate data package in the near future. That will give us much more room for stuff like this. But for now we have to be careful with the space.

**Pull request merged**
