### PR TITLE
drive fix

### PR DESCRIPTION
**Pull request by guga31bb**

### CODE REVIEW

**Comment by guga31bb** [comment]
I *think* this is safe to do now because we started using `order_sequence` to put plays in the right order instead of `drive`, and it fixes #194

**Comment by guga31bb** [comment]
Checked a few games and it seems identical (except for what it's supposed to fix) so I think this is ok to merge in

**Comment by mrcaseb** [comment]
Hm did you mean to close #183 with this PR instead of #194?

**Comment by guga31bb** [comment]
Oops so many win probability issues

**Pull request merged**
