### PR TITLE
Update helper_add_series_data.R

### PR DESCRIPTION
**Pull request by saiemgilani**
move  dplyr::lag(.data$first_down_rush == 1) to dplyr::lag(.data$first_down_rush) == 1

### CODE REVIEW

**Comment by mrcaseb** [comment]
It's pretty clear that it has to be `dplyr::lag(.data$first_down_rush) == 1` but I think we finally need a test for series and drive data @guga31bb. This bug can only affect series in case `first_down_rush == 1 & fixed_drive != dplyr::lag(fixed_drive)`. Are there any cases where this can happen except `fixed_drive` has a bug?

**Comment by mrcaseb** [comment]
And before I forget it, thanks @saiemgilani !

**Comment by guga31bb** [comment]
Looks good to me, thank you!

**Comment by mrcaseb** [comment]
I am going to close this in favor of #133 as the fix in this PR is obsolete because I switched to `first_down` and added the check if the previous play was a touchdown

**Pull request closed without merging**
