### PR TITLE
Implement GSIS ID decoder

### PR DESCRIPTION
**Pull request by mrcaseb**

### CODE REVIEW

**Comment by mrcaseb** [comment]
Also related to https://github.com/mrcaseb/nflfastR-roster/issues/1

**Comment by mrcaseb** [comment]
`clean_pbp()` now decodes the longh pbp IDs to the old GSIS IDs. I have implemented it in a way that every ID column will be decoded. 

However, no we need a data source for the GSIS IDs of new players. So we shouldn't merge this is until this is done.

**Comment by mrcaseb** [comment]
So it looks like we should make the ID decoding optional to prevent scripts and dbs of people out there breaking (see [this tweet](https://twitter.com/dmuney_/status/1308454637138182144?s=20)).

The first thing that came to my mind was `clean_pbp(decode_ids = TRUE)`

What would be your favourite default value - especially for the data repo?

1. `clean_pbp(decode_ids = FALSE)` or

1. `clean_pbp(decode_ids = TRUE)`

**Comment by mrcaseb** [comment]
I wonder if we should move the id decoder into a separate function as it would be muich faster to just decode the ids compared to the whole clean_pbp function. People could use this right before they want to join rosters.

**Comment by guga31bb** [comment]
Yes I think that's a good solution!

**Comment by mrcaseb** [comment]
Going to close this PR because we have a better solution in #94

**Pull request closed without merging**
